manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  opw_kinematics_geometric_parameters:
    a1: 0.000
    a2: -0.070
    b: 0.000
    c1: 0.290
    c2: 0.270
    c3: 0.302
    c4: 0.072
  opw_kinematics_joint_offsets: [ 0.0, 0.0, -1.57079632679, 0.0, 0.0, 0.0 ]
  opw_kinematics_joint_sign_corrections: [ 1, 1, 1, 1, 1, 1 ]
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005